sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: G8OlOXOSKdKvjLOqEy4Rr/qSBn1QGZ26Svf3nZuDDKY8JZFG5aQ678iDsCAFE8tH4OCysnec6LFmIHnrCiYPpErP/KxN0I97e8XuQGPTZbZs7/eNOcOvPWSlQ+N+WVkJTYhmlVt/G+yKzPWGqRBTzqyY7htSrnYJ+eHikcTR1LIo/RVYafQOd+Dy99WHzhemVpvg3QWI9seRAPKQsaovAtROu8nbHj046lozyDRQbRVlFTWvHD7Cv/7uxs5deF8eHzzf2cjTF0Ishmw1WjaBGlUQ+FwsQdo9bjNu+E9WP1tL3IhyC7XWk2D5lAVmo1Db1tFudB3s+gVY5XZpMCRbwKcbL4DMKvD6YJgNAjl2X8YjuOBY5v23E6gio6eAI2GL2dhha+aMFmscTX7KuGCLVAoi8msyt+oiGoINcsUVReOg51n90epG5EmznR/iiDXns8q8InYtaSp5uWPRG34MdoQROjarxcPx2QeGBwd4UHiwCEeUVY+UKdAYY/W51oe2il5+Ylrq9Y+XPHXCKWMiGFjUE7bNjyqMzNY3yBKxSSCIBFtogJ7nBXPdne5rzsuvMmfVFpzHld88BiQlF7IX3fS/9hmN7FLOb5CDL8OQha8QU+nb9oYsbZrdnXqlacJG3EOZVXFTH94L12qBheFv0S4JO0HOmMlkSVigo8hd8w8=
